[package]
name = "lol_timer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = [ "blocking", "json" ] }
futures-io = "0.3"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
